
* Gibbon - Intent Tree Traversal

Turning voice to text transcriptions into actions in an
LLM powered assistant system begins with establishing what
intent caused the user to dictate the text. A simpler way
to think of this is to consider the texts as commands with
arguments. So "add a todo item" or "add this to grocery list"
etc. However it is helpful to capture and recognize
non imperative cues such as "Christmas present idea".

It would also be helpful to be able to determine intent
from context. For example, if the user's last VTT draft
was a paragraph in a letter being dictated, then the
phrase "new paragraph" has a specific contextual meaning.
The same phrase might not mean anything in a different
context.

Although it might be possible to capture all these examples
in a tree of commands and sub commands, that conceptual
structure will eventually lead to friction and poor fit.
So this project uses "intent trees" to associate
the desired disposition of a segment of transcribed text
based on a combination of "action intention" definitions
and current context.

** Context Stacks

There is a tendency of the human mind to have multiple
threads of thought in consideration concurrently, or
at least in a fashion similar to process swapping in
computers. To allow the user to indulge in this practice
the gibbon subsystem can manage multiple concurrent
contexts and recognize intentions to swap or "jump"
from one context to another, and to return to the
previous context.

