

* Overall assistant system architecture


The general structure of the system is a set of isolated tools that
run on a network of machines, sharing resources, state and working
sets via common high level networking protocols such as REST apis
and websockets. The purpose of the system is to provide customized
assistance to one person for the activities that make up that
person's life. It is being developed by the author for personal
use and has zero empahsis on being useful for anyone else, much
less for any short of "production" deployment. All the components,
with the possible exception of LLM services will run on a
private network managed by the user, so no enterprise or internet
class of deployment or security considerations apply.

* Component Breakdown

** Palaver - voice to text component, produces transcribed "drafts"

Working at a basic level. Drafts available via websocket API as
emitted JSON event structures. Drafts available via REST API.

** Gibbon - intent tree traversal tool


Works with "drafts", segments of transcribed voice to determine
what intent the user had when dictating the draft. Uses tree structures
that categorize intents and words or phrases that identify them. Maintains
state so that the intent of one draft can help clarify the intent of the
previous one, a sort of context feature. Supports multiple tree structures
and a stack like context management feature that allows user to
pause context to work on another and then return when done with the side trip.

The output of gibbon is JSON "directives" that contain the original draft,
the located intent tree position and any dynamic properties that
implies such resources like filepaths, evaluated context elements, evaluated
state elements.


* Version one plan sketch (historical interest)

*** Voice to text (Stage 1)

1. Supports voice driven note taking with command prefixes to
   control disposition of note.
2. Supports simple note catalog management to collect notes into
   taxonomies (maybe only one, but maybe multiple, not sure)
3. Supports the process of prompt engineering for prompting LLMs directly
   to review generated text and provide further processing.
4. Supports dictate/review/edit cycles to let human speak freely but
   still avoid LLM context polution.

*** Text to speech (Stage 1)

1. Supports basic playback controls of generated speech, pause, rewind, fast rewind/forward.
2. Supports voice to text annotation of original text
3. Supports display of text with tracking ball during speech, ala sing along with Mitch.

*** Supports basic history functions (Stage 1)

1. On command save of input artifacts (audio, converted-edited text)
2. On command save of output artifacts (result text, annotations)
3. On command grouping for saved artifacts in file system hierarchy fashion
4. On command tagging of saved artifacts and groups with words or short phrases

*** Supports voice commands for managing tool use workflows (Stage 2)

Command recognition and execution for all stage 1 features.


*** Supports history taxonomy (Stage 2)

1. Voice interactive marking of history artifacts with trees of tags
2. Voice interactive expansion/refinement of tag trees into Topic Trees

   
*** Supports structured RAG creation from history (Stage 3)

1. Using typeagent-py, driven by the history Topic Trees, voice interaction
   to construct data collections with mutliple taxonomies.
2. Basic structured RAG augmentation of prompting tools, allowing
   voice interaction loops to identify relevant topics and add
   context to prompts RAG style.

*** Strucuted RAG updates via voice driven MCP interaction (Stage 4)

1. Provide taxonomy meta data in prompts when S-RAG used
2. Voice interaction for appoval/refinement/rejection of data and taxonomy updates
3. Updates through tool into typeagent-py database.

*** Background

This is part of a larger set of projects. Some preliminary thoughts:

I am looking to build custom assistants for various tasks including
normal daily living tasks where note taking and todo list management
are central but access to personal records and historical preferences
and other experienced based guidance likely needed. Another area is
similar but focused on real world project activities in my workshop,
building and maintaining boats, cars, and microprocessor based
electronics projects. Another is software development both for
building the infrastructure for the other tasks, and for other
purposes.

I would like all of this to function via a voice interface
that I can train to understand my specific habits of thought, and
access this via a device I wear on my body to provide full time two
way voice interaction. Building this device will be one of the
microprocessor based projects, and will probably go through many
versions.

I have some experience with esp32 boards and even some experience
doing a voice recorder using an esp32 based watch and a python server
process. I also have some experience with Raspberry PI based projects
for boat systems integration. For the on-body project my current
thinking is that I will use an esp32 board, or if that is inadequate
I'll use an Onion IO Omega 2 as I have some experience with those and
really like them. Or possibly a combination if that helps address the
on-body configuration issues.
